on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: Release Please

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
  
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release.outputs.release_created }}
      
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - name: Zip artifact
        run: |
          zip -r ${{ steps.release.outputs.tag_name }}.zip dist manifest.json rules.json LICENSE
        if: ${{ steps.release.outputs.release_created }}

      - name: Upload artifact to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} ./${{ steps.release.outputs.tag_name }}.zip --clobber
        if: ${{ steps.release.outputs.release_created }}